FROM appiriodevops/ap-microservice-base:0.0.1

MAINTAINER devops@appirio.com

WORKDIR /data

# New Relic configuration file
COPY newrelic.yml /usr/local/share/newrelic/newrelic.yml

# SumoLogic
COPY sumo.conf /etc/sumo.conf
COPY sumo-sources.json ./sumo-sources.json

COPY tech.core.service.identity.jar ./tech.core.service.identity.jar

COPY config.yml ./config.yml

COPY TC.prod.ldap.keystore ./TC.prod.ldap.keystore

COPY run-service.sh ./run-service.sh

CMD ["/bin/bash", "/data/run-service.sh"]

EXPOSE 8080 8081 3306 2181 9092
