authDomain: @auth0.domain@

useResourceAutoRegistering: true

# CORS is configured in Nginx.
#corsSettings:
#  allowedOrigins : "*"
#  allowedMethods : GET,PUT,POST,DELETE,OPTIONS
#  allowedHeaders : Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since
#  allowCredentials : true

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.appirio.tech' to DEBUG.
    com.appirio.tech: DEBUG
    # Logging filter
    com.sun.jersey.api.container.filter.LoggingFilter: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/ap-app.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: /var/log/ap-app-%d.log
      archivedFileCount: 50
      timeZone: UTC

#useShiroAuthorization: false
#iniConfig: shiro.ini

